server:
  port: 8080

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/esports_auth_db?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: tu_contraseña_aqui
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret: 3cfa76ef14937c1c0ea519f8ec0d473a213a4561021438205216382052163820 # Clave segura de prueba (HMAC-SHA)
  expiration: 3600000