server.port=8088
spring.application.name=ranking-service

spring.datasource.url=jdbc:h2:file:./data/rankings
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

feign.client.user-service.url=localhost:8081
feign.client.team-service.url=localhost:8083
feign.client.tournament-service.url=localhost:8084

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
