server.port=8088
spring.application.name=ranking-service

spring.datasource.url=jdbc:mysql://localhost:3306/esports_ranking_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

feign.client.user-service.url=localhost:8081
feign.client.team-service.url=localhost:8083
feign.client.tournament-service.url=localhost:8084