server.port=8083

# Base de datos independiente para Team Service
spring.datasource.url=jdbc:mysql://localhost:3306/esports_team_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuraci�n Hibernate para Spring Boot 4
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Pro-tip para Spring Boot 4: Forzamos el Dialecto en caso de fallos de metadatos JDBC
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Habilitar Interfaz de Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

# Aqu� le decimos a team-service d�nde encontrar el cat�logo de juegos
feign.client.game-service.url=http://localhost:8082

# Aqu� le decimos a team-service d�nde encontrar los perfiles de los jugadores
feign.client.user-service.url=http://localhost:8081