server:
  port: 8085

spring:
  application:
    name: registration-service
  datasource:
    url: jdbc:mysql://localhost:3306/esports_registration_db?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: contraseña
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect