server.port=8081
spring.application.name=user-service

spring.datasource.url=jdbc:mysql://localhost:3306/esports_user_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Activar Swagger UI para User Service
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html