server.port=8085
spring.application.name=match-service

# Configuración de Base de Datos H2 (En archivo local)
spring.datasource.url=jdbc:h2:file:./data/partidas
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa

# Propiedades JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Consola H2 para desarrollo
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Documentación de la API con Springdoc OpenAPI / Swagger UI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/docs/swagger-ui.html

