server.port=8082
spring.application.name=game-service

spring.datasource.url=jdbc:mysql://localhost:3306/esports_game_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Activar Swagger UI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

# Activar Perfil Dev para Faker
spring.profiles.active=dev

# --- SOLUCION CONFLICTO SWAGGER + HATEOAS EN SPRING BOOT 4 ---
springdoc.hateoas.enabled=false
spring.autoconfigure.exclude=org.springdoc.core.configuration.SpringDocHateoasConfiguration